app:
  admin:
    username: ${app-admin-username}
    password: ${app-admin-password}
    initPassword: ${app-admin-initpassword}
    email: ${app-admin-email}

jwt:
  secret: ${jwt-secret-key}
  expiration: ${jwt-expiration}

spring:
  config:
    import: optional:configtree:/run/secrets/

  application:
    name: Task Manager
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://${db-server}:${db-port}/${db-name}
    username: ${db-username}
    password: ${db-password}

  jpa:
    hibernate:
      ddl-auto: validate