spring:
  application:
    name: Task Maganer
  liquibase:
    enabled: true
    change-log: ${CHANGELOG_PATH}

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate